services:
  mysql:
    image: mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - django-app-network
    restart: always
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-uroot","-pTest@123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  nginx:
    image: nginx-app
    build: ./nginx
    container_name: nginx_cont
    ports: 
      - "80:80"
    networks:
      - django-app-network
    depends_on:
       django_app:
         condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  django_app:
    image: aswadayaz/django_app:latest
    build: .
    container_name: django_cont
    command: >
         sh -c "python manage.py migrate &&
         gunicorn notesapp.wsgi:application --bind 0.0.0.0:8000"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    networks:
      - django-app-network
    ports:
      - "8000:8000"
    depends_on:
        mysql:
          condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  django-app-network:

volumes:
  mysql_data:
