services:
  mysql:
    image: mysql:8.0.36
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - django-app-network
    restart: always
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-uroot","-pTest@123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  nginx:
    image: nginx-app
    build: ./nginx
    container_name: nginx_cont
    ports: 
      - "80:80"
    networks:
      - django-app-network
    depends_on:
       django_app:
         condition: service_healthy
    restart: always

  django_app:
    image: django_app
    build: .
    container_name: django_cont
    env_file:
      - .env
    networks:
      - django-app-network
    depends_on:
        mysql:
          condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  django-app-network:

volumes:
  mysql_data:
